version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  web:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  redis:
    image: "redis:latest"
    env_file:
      - .env
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
