version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  web:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    command: python server.py runserver --host=0.0.0.0 --port=8000
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - backend

  celery:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - backend

  celery_beat:
    build: .
    command: celery -A worker.celery beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - web
      - redis
    networks:
      - backend

  redis:
    image: "redis:latest"
    env_file:
      - .env
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
